### ISSUE TITLE
Any Plans On Updating Raycast Store?

### ISSUE THREAD

**Issue by vkhitrin** [InteractiveNinja/raycast-linkding-ext#1]
Hey @InteractiveNinja, I enjoy this extension a lot :)
I am using your repository since it has some additional stuff not published in the Raycast store.

Are you planning to push those changes to [raycast/extensions](/raycast/extensions)?

**Comment by InteractiveNinja** [comment]
Hey @vkhitrin, thanks for reminding me that I never finished the update for this extension 😄 

Going to push some things today and will try to push it to [raycast/extensions](https://github.com/raycast/extensions) this week.

**Comment by InteractiveNinja** [comment]
Created a PR for the store https://github.com/raycast/extensions/pull/9129 🤞

**Comment by InteractiveNinja** [comment]
Got merged 👍
